childbirths-profile:  
  target: dev  
  outputs:    
    dev:      
      type: postgres      
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"     
      user: "{{ env_var('DBT_POSTGRES_USER') }}"     
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"      
      port: 5432     
      dbname: "{{ env_var('DBT_POSTGRES_DB') }}"      
      schema: "{{ env_var('DBT_DBT_SCHEMA') }}"      
      threads: 1      
      keepalives_idle: 0 # default 0, indicating the system default      
      connect_timeout: 10 # default 10 seconds