version: '3.8'

services:

  dbt-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbtuser
      POSTGRES_PASSWORD: dbtpassword
      POSTGRES_DB: dbtdatabase
      DBT_SCHEMA: dbt
      DBT_RAW_DATA_SCHEMA: dbt_raw_data
    expose:
      - 5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
      - ./scripts_postgres_dbt:/docker-entrypoint-initdb.d

  airflow-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER : airflowuser
      POSTGRES_DB : airflowdb
      AIRFLOW_SCHEMA: airflow
    expose:
      - 5432
    volumes:
      - ./scripts_postgres_airflow:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - airflow-db
      - dbt-db

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

  airflow:
    build: .
    restart: always
    ports:
      - 8000:8080
    environment:
      DBT_PROFILES_DIR: /dbt
      AIRFLOW_HOME: /airflow
      AIRFLOW__CORE__DAGS_FOLDER: /airflow/dags
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__DAG_CONCURRENCY: 4
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4
      # AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS: False
      # Postgres details need to match with the values defined in the postgres service
      POSTGRES_USER: airflowuser
      POSTGRES_PASSWORD: pssd
      POSTGRES_HOST: airflow-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflowdb
      # postgres-dbt connection details. Required for the inital loading of seed data# Credentials need to match with service postgres-dbt
      DBT_POSTGRES_PASSWORD: dbtpassword
      DBT_POSTGRES_USER : dbtuser
      DBT_POSTGRES_DB : dbtdatabase
      DBT_DBT_SCHEMA: dbt
      DBT_DBT_RAW_DATA_SCHEMA: dbt_raw_data
      DBT_POSTGRES_HOST: dbt-db
      SNF_UNAME: ${SNF_UNAME}
      SNF_PWD: ${SNF_PWD}
    depends_on:
      - airflow-db
      - dbt-db
    volumes:
      - ./dbt:/dbt
      - ./airflow:/airflow
      - ./python:/python
      - ./datafiles:/datafiles

volumes:
  pg-data: