#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
 ALTER ROLE $POSTGRES_USER SET search_path TO $DBT_SCHEMA;
 CREATE SCHEMA IF NOT EXISTS $DBT_SCHEMA AUTHORIZATION $POSTGRES_USER;
 CREATE SCHEMA IF NOT EXISTS $DBT_RAW_DATA_SCHEMA AUTHORIZATION $POSTGRES_USER;
 --CREATE SCHEMA IF NOT EXISTS $AIRFLOW_SCHEMA AUTHORIZATION $POSTGRES_USER;
 
SET datestyle = “ISO, DMY”;
EOSQL